### ISSUE TITLE
help pls

### ISSUE THREAD

**Issue by dewydrops** [gfish/queue_it#13]
hi, you guys seem to be familiar with queue it so if yall don't mind i have some questions 🥹 idk how else to contact you guys so sorry

**Comment by dewydrops** [comment]
if possible i would like to ask for your help privately since i just realised this is an open discussion :')..

**Comment by mproqueueit** [comment]
Please write to ***@***.*** and I'll pick it up.

/Martin
________________________________

**Comment by dewydrops** [comment]
sorry how do i contact you?

**Comment by mproqueueit** [comment]
Please write an email with your questions to ***@***.*** and I'll pick it up.

/Martin

/Martin


________________________________

**Comment by dewydrops** [comment]
testing

**Comment by dewydrops** [comment]
sorry i dont get it because if i reply to the email it shows up here

**Comment by mproqueueit** [comment]
Ohh - emails are removed by GitHub.
Please try support at queue-it dot com

/Martin


________________________________

**Comment by dewydrops** [comment]
ah i see I just dropped an email thank you :)
