### ISSUE TITLE
Rails 4.x support

### ISSUE THREAD

**Issue by pawelpacana** [gfish/queue_it#2]
https://github.com/gfish/queue_it/blob/master/lib/queue_it/queueable.rb#L20 relies on API that is not present anymore.

See: https://github.com/rails/rails/blob/a1ec4da291dd3e0705be536e71a963d8d356ff24/actionpack/lib/action_dispatch/request/session.rb#L6

**Comment by pawelpacana** [comment]
@kaspergrubbe any progress on this one?

**Comment by kaspergrubbe** [comment]
Feel free to patch your changes in, and release a version 2.0.0 of this gem.

Eventually just make a PR, and I will do the release part.

**Comment by kaspergrubbe** [comment]
@pawelpacana

**Comment by jakubkosinski** [comment]
@kaspergrubbe @pawelpacana I've just made a fix in #4
